export const currencies = [
  { code: 'USD', name: 'US Dollar', symbol: '$', symbol_position: 'before', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'EUR', name: 'Euro', symbol: '€', symbol_position: 'before', decimal_places: 2, thousand_separator: '.', decimal_separator: ',' },
  { code: 'GBP', name: 'British Pound', symbol: '£', symbol_position: 'before', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', symbol_position: 'before', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', symbol_position: 'before', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', symbol_position: 'before', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', symbol_position: 'before', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', symbol_position: 'after', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', symbol_position: 'after', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', symbol_position: 'before', decimal_places: 0, thousand_separator: ',', decimal_separator: '.' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', symbol_position: 'before', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', symbol_position: 'before', decimal_places: 2, thousand_separator: "'", decimal_separator: '.' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', symbol_position: 'after', decimal_places: 2, thousand_separator: ' ', decimal_separator: ',' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', symbol_position: 'after', decimal_places: 2, thousand_separator: ' ', decimal_separator: ',' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', symbol_position: 'after', decimal_places: 2, thousand_separator: '.', decimal_separator: ',' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', symbol_position: 'before', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', symbol_position: 'before', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', symbol_position: 'before', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', symbol_position: 'before', decimal_places: 2, thousand_separator: '.', decimal_separator: ',' },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'MX$', symbol_position: 'before', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', symbol_position: 'before', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', symbol_position: 'before', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', symbol_position: 'before', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', symbol_position: 'before', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: '₨', symbol_position: 'before', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', symbol_position: 'before', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KD', symbol_position: 'before', decimal_places: 3, thousand_separator: ',', decimal_separator: '.' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'QR', symbol_position: 'before', decimal_places: 2, thousand_separator: ',', decimal_separator: '.' },
  { code: 'OMR', name: 'Omani Rial', symbol: 'OR', symbol_position: 'before', decimal_places: 3, thousand_separator: ',', decimal_separator: '.' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: 'BD', symbol_position: 'before', decimal_places: 3, thousand_separator: ',', decimal_separator: '.' },
];

export const defaultCountries = [
  { country_code: 'US', country_name: 'United States', currency_code: 'USD', flag_emoji: '🇺🇸' },
  { country_code: 'GB', country_name: 'United Kingdom', currency_code: 'GBP', flag_emoji: '🇬🇧' },
  { country_code: 'IN', country_name: 'India', currency_code: 'INR', flag_emoji: '🇮🇳' },
  { country_code: 'CA', country_name: 'Canada', currency_code: 'CAD', flag_emoji: '🇨🇦' },
  { country_code: 'AU', country_name: 'Australia', currency_code: 'AUD', flag_emoji: '🇦🇺' },
  { country_code: 'DE', country_name: 'Germany', currency_code: 'EUR', flag_emoji: '🇩🇪' },
  { country_code: 'AE', country_name: 'United Arab Emirates', currency_code: 'AED', flag_emoji: '🇦🇪' },
  { country_code: 'SG', country_name: 'Singapore', currency_code: 'SGD', flag_emoji: '🇸🇬' },
];
